### ISSUE TITLE
Remove obsoleted stix-shifter data sources

### ISSUE THREAD

**Issue by subbyte** [opencybersecurityalliance/federated-search-end-to-end-testing#4]
May consider remove `bh22-win02` and `bh22-linux01` in `config/kestrel-stixshifter-config.yml` since they are not used any more.

**Comment by cmadam** [comment]
Addressed in commit https://github.com/opencybersecurityalliance/hunting-stack-testing/commit/1f3958cdbaf7afae759dcd8ce57df4b0e73f0ed6
